// Generated by https://quicktype.io

export interface User {
  id:   number;
  name: string;
}

export interface Company {
  id:     number;
  userId: number;
  name:   string;
}

export interface Truck {
  id:        number;
  companyId: number;
  brand:     string;
}
